export const state = {
    source: null,      // { lat, lng, name }
    dest: null,        // { lat, lng, name }
    allRoutes: [],
    currentRouteIndex: 0,
    currentRouteObj: null,
    currentRoute: [],
    isNavigating: false,
    sessionId: null,
    carPos: null,
    distanceLeft: 0,
    stepProgress: 0,
    currentRoadIndex: 0,
    debugRouteInspector: false,
    debugCarsVisible: true,
    recommendedSpeeds: new Map(),
    pendingEdgeEvents: [],
    currentEdgeTimeMs: 0,
    driverProfile: null,
    motionState: null,
    navDebug: null,
    simulationCars: [],
    offRouteOffset: [0, 0],
    isDrifting: false,
};
